spring.datasource.url=jdbc:${NEON_DB_URL}
spring.datasource.username=${NEON_DB_USERNAME}
spring.datasource.password=${NEON_DB_PASSWORD}

spring.datasource.driver-class-name=org.postgresql.Driver
aws.s3.bucket=${AWS_S3_BUCKET}
spring.sql.init.mode=always
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB